<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <BlazorDisableThrowNavigationException>true</BlazorDisableThrowNavigationException>
  </PropertyGroup>

  <PropertyGroup Condition="'$(Configuration)' == 'Release'">
    <ContainerBaseImage>mcr.microsoft.com/dotnet/aspnet:10.0-noble-chiseled</ContainerBaseImage>
    <ContainerImageTag>latest</ContainerImageTag>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\..\source\user-interface-ui\HolisticWare.AddressBook.UserInterfaceUI.Razor\HolisticWare.AddressBook.UserInterfaceUI.Razor.csproj" />
  </ItemGroup>

</Project>